{% set name = "clingo" %}
{% set version = "5.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/clingo/archive/v{{ version }}.tar.gz
  sha256: 2891ecfcccbe728168ac27d62c3036aae0164b15b219b4954fb18614eda79f53
  patches:
    - find-python.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - cffi  # [python_impl == 'cpython']

test:
  commands:
    - clingo --version
    - clasp --version
    - reify --version
    - lpconvert --version
    - gringo --version

about:
  home: https://potassco.org/
  license: MIT
  summary: A grounder and solver for logic programs.
  description: Clingo is an answer set programming (ASP) system that takes a logic program as input and calculates its answer sets.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
