{% set name = "clingo" %}
{% set version = "5.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/clingo/archive/v{{ version }}.tar.gz
  sha256: ac6606388abfe2482167ce8fd4eb0737ef6abeeb35a9d3ac3016c6f715bfee02
  
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - make  # [unix]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

test:
  commands:
    - clingo --version
    - clasp --version
    - reify --version
    - lpconvert --version
    - gringo --version

about:
  home: https://potassco.org/
  license: MIT
  summary: A grounder and solver for logic programs.
  description: Clingo is an answer set programming (ASP) system that takes a logic program as input and calculates its answer sets.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
